from gmail_sender import send_gmail_to_people_in_list
from gmail_sender import send_html_gmail_to_people_in_list
from gmail_sender import send_gmail_to_one
from gmail_sender import send_html_gmail_to_one